### ISSUE TITLE
Check for WebRTC

### ISSUE THREAD

**Issue by szepeviktor** [saljam/webwormhole#24]
My browser is quite restricted, e.g. WebRTC is disabled.

I see an error on the browser console that `RTCPeerConnection` is not defined.

Could you check the availability of WebRTC before using it?
Thanks.

**Comment by saljam** [comment]
It now shows a message if the browser is missing a required feature.
<img width="641" alt="screenshot" src="https://user-images.githubusercontent.com/751023/80855162-a8572100-8c0c-11ea-99f8-6717b9394174.png">

(Technically, we don't use WebSockets right now but I'm experimenting with changing the signalling protocol to use them, in order to make trickle-ice easier.)

**Comment by szepeviktor** [comment]
Thank you.
