### ISSUE TITLE
Indicate NAT level

### ISSUE THREAD

**Issue by lxgr** [saljam/webwormhole#31]
Since successful STUN-mediated NAT traversal requires at least one side of the connection to be on something better than a symmetric NAT, how about a visual indicator for this? Heuristic detection of the NAT type seems to be possible in WebRTC: https://webrtchacks.com/symmetric-nat/

How about something like a traffic light, yellow for symmetric NAT or worse, green for a traversable NAT, and maybe red for blocked UDP (assuming this is detectable by a STUN server not being reachable at all in the test)?

It would not be 100% accurate (IPv6 paths can be different from v4 and possibly many other reasons), but the semantics would be roughly that for two users with yellow lights, or one with a red light, there will probably not be a P2P connection, saving everybody some time and frustration.

**Comment by saljam** [comment]
I like this idea.

In general I'd also like better client-side logging of what happens when a connection can't be established. Maybe have a link for "debug.txt" that logs more of the signalling and webrtc state (with private information like filenames and ip addresses removed) that people can attach when reporting issues.

**Comment by lxgr** [comment]
That sounds good!

Related to this, I also just noticed that apparently peer reflexive connections aren't possible with WebWormhole. Is this a known problem, or should I open a separate issue for this?

**Comment by saljam** [comment]
I agree, a warning would do the job.

Re: peer reflexive addresses. Good point. The current version of the signalling protocol did not trickle ICE, and I *believe* that's the reason for this and a bunch of other connectivity issues. At least in some browser combinations.

I'm working on a version that trickles ICE over WebSockets and it seems to work much better. E.g. iOS Safari to iOS Safari works for me on the same network where previously it didn't.

It's a breaking change. I'll have it on a staging domain tonight to test first.

**Comment by lxgr** [comment]
Ah, interesting! I tried the same thing over the weekend actually but did not get anywhere with it: Chrome and Safari just would not expose peer reflexive candidates to JavaScript (I also assumed that not relaying these was the cause of this issue).

However, chrome actually seems to be using peer reflexive candidates just fine without exposing them in JavaScript. They are visible in the getStats() call though and are definitely used: I could establish a connection between a client behind a full-cone NAT and a symmetric NAT.

I doubt that even with trickled candidates, the very large classes of port-restrictive <-> symmetric and symmetric <-> symmetric connections will become possible: As far as I understand it, if one side is symmetric, the other needs to be at least address-restricted full cone or better.

By the way, this is quite tangential, but if you give your site microphone or camera permissions, you can see several additional candidates appear during ICE, importantly IPv6 candidates in my test (which does allow a connection between my symmetric NAT test connection and my port-restricted NAT, as both have firewalled but non-translating IPv6). This is explained [here](https://tools.ietf.org/html/draft-ietf-rtcweb-ip-handling-12), but at least Chrome does not seem to adhere to the "Mode 2" specification listed there, given that it does not expose an IPv6 candidate in that mode.

**Comment by saljam** [comment]
Thanks for the link, I've not read that one before.

Yeah, there'll always be cases where no amount of STUN will make it work. I did notice that Safari was providing more candidates if I trickled NAT. I had no idea why, the "modes" spec does shed some light on what goes into the candidate selection though.

There isn't really much I can think of to change this short of running a TURN server. So... I might just do that. There's plenty of spare capacity on the machine running the signalling server, there's no reason not to allocate a quota of it for relaying. And when it runs out, it gets replenished end of the month. (I'll need to figure out auth so that tokens are generated and given with slots by the signalling server.)

**Comment by saljam** [comment]
I've hacked together something similar to https://webrtchacks.com/symmetric-nat/ in both the command line and web versions. It checks the mapping between internal and external ports and tries to guess. I guess we can do a lot more probing but for now it's probably better to point people to https://test.webrtc.org/.

Considering there's nothing actionable that someone can do with this information to make the connection work I'm hesitant to put it in the UI. I'm convinced to make this work seamlessly we need TURN. That said, it's printed in the web console:
<img width="613" alt="console" src="https://user-images.githubusercontent.com/751023/81601641-1ea11380-93c3-11ea-80b7-13cff1db0f71.png">

BTW I just tried, Firefox also does not use IPv6 addresses without video permissions. That's a bummer. I'm not entirely sure I understand the privacy benefits of this, since the connection to the signalling server is already over IPv6.
