### ISSUE TITLE
generate connection failure log/report

### ISSUE THREAD

**Issue by tyehle** [saljam/webwormhole#37]
When a connection fails there isn't any indication about why. It would be nice to have this to track down problems such as #26 

Maybe adding some `Console.log` messages would help, though doing that from the WASM seems like it might be a pain. @saljam, did you have plans to do any other sort of logging?

**Comment by saljam** [comment]
Go's fmt.Println goes to the console too, it shouldn't be too bad.

**Comment by saljam** [comment]
[this commit](https://github.com/saljam/webwormhole/commit/f06f470dec2006d5adb4bbb8cc6b1003405d2101) added slightly more liberal logging to console. i'd like to also log more of the RTCPeerConnection callback (oniceconnectionstatechange, onconnectionstatechange, onsignalingstatechange)

in #31 an idea was floated to add a link to a generated text file folks can attach to reports. maybe make it appear on failure or after a certain time of waiting for a connection to be established?

**Comment by saljam** [comment]
https://github.com/saljam/webwormhole/commit/e92e51856f5f503b5efb2c39897e7cf6f6235e95

**Comment by saljam** [comment]
I think we have enough visibility for now with:
- subscribing to chome/safari's preferred method for signalling connection status change
- logging more to web console
- adding the -verbose flag to the command line tool
- and printing the candidate/NAT summary line (#31)

<img width="613" alt="console" src="https://user-images.githubusercontent.com/751023/81605288-25328980-93c9-11ea-9462-774969d93cf7.png">

I've toyed with printing the offer and answer SDP as well, but these contain private data (IP addresses) that I don't want folk to copy and paste here by accident. So I've removed the in favour of pointing to where they can be found (about:webrtc and chrome://webrtc-internals/). If it turns out we need those we can always add them back to the logs.
