### ISSUE TITLE
configurable default wormhole server

### ISSUE THREAD

**Issue by jankatins** [saljam/webwormhole#44]
I found `ww -signal https://<wormhole.domain>.com send <file>` but is there also a way to set these config values in a config file so a specific server is always used?

**Comment by saljam** [comment]
There's no config file at the moment, and I'm hesitant to add one since I'd like to keep things simple.

You could set up an [alias](https://tldp.org/LDP/abs/html/aliases.html) for your shell that adds the `-signal https://example.com` option right now.

If that's not enough would an environment variable work in your case?

**Comment by jankatins** [comment]
Yes, env would work as well, just something I can in some way set as a default on my logins.
