### ISSUE TITLE
Question `Wormhole.addCandidates`

### ISSUE THREAD

**Issue by lucasmrod** [saljam/webwormhole#61]
Hi! First of all, I love the tool :)

Now to the question, I'm reading the source code to understand how it all works and I don't follow the `Wormhole.addCandidates` code: https://github.com/saljam/webwormhole/blob/36a849689816da113f571fc0c8bc8ab89d089b60/wormhole/dial.go#L251 where is the corresponding `writeEncJSON` with the candidate data?

Let me know if opening an issue is not the best medium for this kind of questions.

**Comment by saljam** [comment]
There isn't one yet!

By default, the pion library collects all candidates and puts them in the offer or answer. So we can safely remove addCandidates and the command line client would still work. However, because the javascript client sends over candidates individually we have to support adding them if we want this to interoperate with the browser version.

This is called "trickle-ice" and it's done because collecting candidates can sometimes take a while. Think setting up relays, asking STUN servers, etc. This allows us to generate the offer or answer faster and send candidates whenever they are ready.

The go code should also do it at some point, I just didn't get around to it. Looking at pion docs, it shouldn't be too hard to add.

We'll need to attach to this callback: https://pkg.go.dev/github.com/pion/webrtc/v2?tab=doc#PeerConnection.OnICECandidate
And probably enable this: https://pkg.go.dev/github.com/pion/webrtc/v2?tab=doc#SettingEngine.SetTrickle

**Comment by saljam** [comment]
It's fine to open issues for questions, since we haven't got a better place. Feel free to close this if it makes sense to you.

**Comment by saljam** [comment]
now implemented in https://github.com/saljam/webwormhole/blob/337d4ecbbb2c1ddb243f82e5186b9d9692ac89a6/wormhole/dial.go#L465

**Comment by lucasmrod** [comment]
That all makes sense. Thanks for the clarification!

A couple of thoughts/questions:
1. For `c.pc.OnICECandidate` to make effect in the command line domain (`ww send` + `ww receive`), shouldn't `go c.addCandidates(ws, &key)` be called before sending offer/answer? 
2. Interop: How did the browser get candidates from the command line app (`ww `) before the addition of `c.pc.OnICECandidate`?

**Comment by saljam** [comment]
1. Are you concerned about the race condition of remote candidates arriving before that goroutine is running? That's not a problem, they'll just sit in the websocket buffer until `addCandidates` calls `readEncJSON`.

There *is* a race that we should fix though, and thanks pointing it out: [OnICECandidate](https://rtcweb-wg.github.io/jsep/#rfc.section.4.1.9) starts triggering after `pc.SetLocalDescription()` is called, so we should send the offer/answer before setting it as the local description, lest we send a candidates before the offer/answer.

(Aside: The whole RTCPeerConnection API is a little idiosyncratic and callback-heavy. It's an almost 1:1 copy of the JS API, which itself is also a bit weird, even for a browsers API! I can see why pion did it this way though. It makes targetting WASM easier.)

2. The webrtc package synchronously collected and appended them as "candidate" lines to the offer or answer body, during `pc.CreateOffer()` or `pc.CreateAnswer()`. `SetTrickle` makes it asynchronous.

**Comment by lucasmrod** [comment]
> There is a race that we should fix though, and thanks for pointing it out: OnICECandidate starts triggering after pc.SetLocalDescription() is called, so we should send the offer/answer before setting it as the local description, lest we send a candidates before the offer/answer.

On second thought, (1) was wrong, we really can't call `addCandidates` before offer/answer.
But the race you fixed makes sense :)

> The webrtc package synchronously collected and appended them as "candidate" lines to the offer or answer body, during pc.CreateOffer() or pc.CreateAnswer(). SetTrickle makes it asynchronous.

Makes sense (I may need to read WebRTC specs to understand these details).

Thanks for all the info. Really useful!
