### ISSUE TITLE
[feature suggestion] able to specify source (binding) IP address

### ISSUE THREAD

**Issue by mailinglists35** [saljam/webwormhole#69]
in some rare cases where you need to quickly/easily get data out of systems where default gateway goes to a closed network.
I would be nice but not a priority to be able to specify the source IP address to choose to initiate the outgoing connection.
https://formin97.tistory.com/234

_also perhaps I should file a separate detailed issue, it would also be useful to be able to traverse http proxies (I have setup the http_proxy environment variable for the cli but I can't get the browser and the cli to connect)_

**Comment by saljam** [comment]
for the bind address, i'm a bit hesitant to add special-case options for rare scenarios. especially if it can be accomplished in a different way, e.g. using network namespace on linux. this [superuser](https://superuser.com/questions/271915/route-the-traffic-over-specific-interface-for-a-process-in-linux) question has some answers explaining how to do that. it's not perfect, since it requires root, but it's possible. (the LD_PRELOAD answer is probably not going to work since this is written in go.)

i'll close this issue since i won't work on it any time soon, but if many people request the same thing i'm happy to reconsider.

as for the proxy, the connection to the signalling server currently does respect the HTTP_PROXY environment variable so if both machines are behind the proxy and can get a direct connection it should still work. however, relay (TURN) connections currently don't. the webrtc library we use added proxy support for TURN connections in its v3 beta. as soon as v3 is released i'll upgrade and make it respect HTTP_PROXY.

**Comment by mailinglists35** [comment]
> using network namespace on linux

hah, cool, looks interesting, thank you. will try that next time I need to get something from that box

**Comment by mailinglists35** [comment]
>the webrtc library we use added proxy support for TURN connections in its v3 beta. as soon as v3 is released i'll upgrade and make it respect HTTP_PROXY.

I would like to try the beta version. Would you mind a little help pointing to instructions to make it work with the v3 beta of that library? Thank you!

**Comment by mailinglists35** [comment]
update: I managed to get it working with [firejail](https://unix.stackexchange.com/a/498140): instead of setting up cgroups and namespaces and iptables manually, firejail can do everything automatically and transparently and exit cleanly:

`firejail --dns=8.8.8.8 --noprofile --net=eth0 --ip=192.168.1.1 HOME/go/bin/ww send filename`

but would still be interested to have the full proxy version working as well :)

**Comment by saljam** [comment]
>I would like to try the beta version. Would you mind a little help pointing to instructions to make it work with the v3 beta of that library? Thank you!

sure!

1. first we've got to get the new package. i think `go get github.com/pion/webrtc/v3` should do the job
2. replace github.com/pion/webrtc/v2 with github.com/pion/webrtc/v3 everywhere in the project
3. lastly, configure it to use the proxy from the environment (probably somewhere [here](https://github.com/saljam/webwormhole/blob/99f4f1980440dbb72d1d0587f951a314c689595d/wormhole/dial.go#L287))

according to the docs that's done with [SettingEngine.SetICEProxyDialer()](https://pkg.go.dev/github.com/pion/webrtc/v3#SettingEngine.SetICEProxyDialer). so, in theory, if we pass ["golang.org/x/net/proxy".FromEnvironment()](https://pkg.go.dev/golang.org/x/net/proxy#FromEnvironment) to SetICEProxyDialer it should respect the HTTP_PROXY. but i haven't tried this.

> I managed to get it working with firejail

that's awesome! thanks for sharing the command.

**Comment by saljam** [comment]
i just pushed this to a new branch, s/proxy. v3 seems to work. (well, the ICE trickle option was removed, i'll need investigate whether it's now enabled by default or there's a different way to enable it.)

i did not have the time to test whether proxy support actually works but it's there if you want to play with it.

**Comment by mailinglists35** [comment]
Finally had some time to test the new version for the proxy support.

What I found is the initial connection to server is done via http proxy (squid logs` TCP_TUNNEL/200 4728 CONNECT wrmhl.link:443 - HIER_DIRECT/167.71.188.1`), however the effective transfer happens over direct UDP  connection. Is this somehow by design of the webwormhole protocol? If yes, then any attempt at using a http proxy would fail.

**Comment by saljam** [comment]
You're absolutely right. WebRTC DataChannels are UDP only, as opposed to Audio/Video which can use TCP. TURN proxy support is a red herring and won't help. (Doh! I even knew this but didn't think it through when I saw the proxy option in Pion!)
