### ISSUE TITLE
IOS 14.5.1 receiver prompts for download, get 189 byte file instead

### ISSUE THREAD

**Issue by lazerhawk** [saljam/webwormhole#92]
Looks like the iOS bug is back on 14.5.1

#72

**Comment by saljam** [comment]
i finally got around to upgrade to 14.5.1 (from 14.4.2) but i can't reproduce this.

can you share more about your setup? do you have any plugins enabled or settings modified?

**Comment by lazerhawk** [comment]
Same iPad as last time, fully updated. No plugins that I can see. As far as I am aware, no settings have been modified from default by the iPad user.

Sender tried on Firefox and Edge

Get prompted for the download, but it drops the 189 byte file

The 189 byte file reads

"Oops. You're not supposed  to end up here.

This URL is used by WebWormhole to efficiently download data from a web page. It is usually handled by a ServiceWorker running in your browser"

Maybe there's a privacy setting change I am not aware of?

**Comment by lazerhawk** [comment]
Ah, but the guy sitting next to me with his iPhone 14.5.1 did work just now...

**Comment by saljam** [comment]
aha! have you got "request desktop version" option enabled on the ipad? i can reproduce it with that. turning it off fixes it.

gonna have to revisit why service workers download doesn't work on safari so we can remove this exception.

and if that fails, i guess more user agent heuristics to catch all incantations of safari 🤷 .

**Comment by increpare** [comment]
(I too used to have this problem but was too lazy to put together a report, but it seemed to work ok today fwiw)

**Comment by saljam** [comment]
@increpare do you remember roughly when it was broken for you? before or after december 2020?

**Comment by increpare** [comment]
It was happening since december for sure.  I just tried it to make sure, and connecting with ios safari and edge windows (edge hosting), I can send a picture from iOS -> PC but in the other direction I get the 

```Oops. You're not supposed to end up here.

This URL is used by WebWormhole to efficiently download data from
a web page.  It is usually handled by a ServiceWorker running in
your browser.
```

file.

**Comment by lazerhawk** [comment]
> 
> 
> aha! have you got "request desktop version" option enabled on the ipad? i can reproduce it with that. turning it off fixes it.
> 
> gonna have to revisit why service workers download doesn't work on safari so we can remove this exception.
> 
> and if that fails, i guess more user agent heuristics to catch all incantations of safari shrug .

Yes! that fixed it! Gah, what dumb thing get stuck on...

Hrm, so is there a way to kick safari on iOS to mobile site mode when safari is set to request desktop mode by default, or post a link on the wormhole page to select a mobile only mode if you can't heuristically detect that is occurring perhaps?

**Comment by saljam** [comment]
so the root of the issue is that safari doesn't support streaming downloads from service workers. i thought maybe i wasn't holding it right but there's tickets upstream for it:

https://bugs.webkit.org/show_bug.cgi?id=182848
https://bugs.webkit.org/show_bug.cgi?id=202142

i guess at this point we can either:
1. try to probe for this programmatically: try to stream a small file to fetch() on startup and if we get the 404 disable service workers? not sure if this will add noticeable latency or even work at all.
2. or do more clever user-agent parsing. the current test is `if (window.safari || /iPad|iPhone|iPod/.test(navigator.userAgent))`. [this page](https://developer.mozilla.org/en-US/docs/Web/HTTP/Browser_detection_using_the_user_agent#which_part_of_the_user_agent_contains_the_information_you_are_looking_for) says chrome also sends 'safari' in its user-agent, so to detect actual safari the ua must contain 'safari' and must not contain 'chrome' or 'chromium'.

i think i'll do 2. it's kinda gross, but should make it work on ipads regardless of the 'request desktop version' setting.

p.s. i should probably reword the text in that blob to clarify that it's a dummy URL used to make browsers stream downloads from a direct webrtc connection.

**Comment by saljam** [comment]
i just pushed a version that does more user-agent sniffing. if that doesn't fix the issue please reopen! (it does on my phone but I don't have an ipad to test)

**Comment by increpare** [comment]
Just confirming with safari on ipad and edge on pc that I can now send
files in both directions in both desktop mode as well as mobile mode.
Thanks!

‪Am Sa., 29. Mai 2021 um 14:14 Uhr schrieb ‫سلمان الجماز‬‎ <
***@***.***>:‬

**Comment by lazerhawk** [comment]
> 
> 
> i just pushed a version that does more user-agent sniffing. if that doesn't fix the issue please reopen! (it does on my phone but I don't have an ipad to test)

Works both modes on my iPad. Thanks for digging into this! Webwormhole is a real lifesaver!
