### ISSUE TITLE
Regression: "Could not connect" on Firefox 68.9.0 Android

### ISSUE THREAD

**Issue by richfelker** [saljam/webwormhole#95]
Creating or attempting to connect to a webwormhole produces an error "Could not connect" with no further details on mobile (Android) Firefox 68.9.0. I can't easily upgrade to a different version because all later versions removed `about:config` except in nightly and moving all config/data over to a different app (nightly) is nontrivial.

**Comment by saljam** [comment]
Thanks for reporting this!

The only recent change we made that interacts with web APIs is the getStats() call for WebRTC. Maybe Firefox 68 doesn't like how we use that?

In any case, if this used to work until recently I see no reason we can't be backwards compatible. I'll download an android image and try to figure out what went wrong.

**Comment by saljam** [comment]
turns out [class field syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Public_class_fields) was not supported by firefox 68:

	SyntaxError: Fields are not currently supported webwormhole.js:5:1

i've removed our usage of class fields, and it fixed it on my firefox 68. @richfelker let me know if you still have any issues.

it sounds like it's time to look into using babel or whatever the current js-to-js compiler of the day is. (maybe finally move to typescript?)
